# Header
navname: czxieddan's Blog

# navigatior items
nav:
  Posts: /archives
  Categories: /category
  Tags: /tag
  About: /about

# favicon
favicon: /favicon.ico

# Profile
nickname: czxieddan

### this variable is MarkDown form.
description: Keep in mind czxieddan meow.
avatar: /image/czxieddan.jpg

# main menu navigation
## links key words should not be changed.
## Complete url after key words.
## Unused key can be commented out.
links:
  Blog: /archives
  # Category:
  # Tags: 
  # Link:
  # Resume:
  # Publish:
  # Trophy:
  # Gallery:
  # RSS:
  # AliPay:
  # ZhiHu:
  # LinkedIn:
  # FaceBook:
  Twitter: https://x.com/CzXieDdan
  # Skype:
  # CodeSandBox:
  # CodePen:
  # Sketch:
  # Gitlab:
  # Dribbble:
  # Instagram:
  # Reddit:
  # YouTube:
  QQ: https://czxieddan.top/2024/06/06/jump/#QQID
  # Weibo: 
  WeChat: https://czxieddan.top/2024/06/06/jump/#WeChatID
  Github: https://github.com/czxieddan/czxieddan.github.io
  # URL: https://github.com/czxieddan/czxieddan.github.io
  Douyin: https://www.iesdouyin.com/share/user/MS4wLjABAAAA5s_ASGtsXCZRmGz0Wq3mJrzUi0dJ5dGAIyKGhaz_eRQ?u_code=81id2l6aci1&did=MS4wLjABAAAAT8R741uVn-JZsIC2-IARG6p7bOfkW7pRC_Wlt2uqxLWymQakH7rDctnXr-b1NiTf&iid=MS4wLjABAAAAHX_Y4GYpQjel92EcNO2IGMLzsfp9iA_8CXfb_J4XSEk&with_sec_did=1&sec_uid=MS4wLjABAAAA5s_ASGtsXCZRmGz0Wq3mJrzUi0dJ5dGAIyKGhaz_eRQ&from_ssr=1&from_aid=1128&timestamp=1720082410&utm_source=copy&utm_campaign=client_share&utm_medium=android&app=aweme&life_share_ext=%7B%22life_share_id%22%3A%22ef788780bc8e4b6b9aa3e2677b812d1b%22%2C%22from_user_id%22%3A334667535878984%2C%22enter_from%22%3A%22others_homepage%22%2C%22personal_enter_page%22%3A%22homepage_hot%22%2C%22personal_enter_method%22%3A%22slide%22%7D&activity_info=%7B%22social_author_id%22%3A%22334667535878984%22%2C%22social_share_id%22%3A%22334667535878984_1720082408148%22%2C%22social_share_time%22%3A%221720082410%22%2C%22social_share_user_id%22%3A%22334667535878984%22%7D


# how links show: you have 2 choice--text or icon.
links_text_enable: false
links_icon_enable: true

# Post page
## Post_meta
post_meta_enable: true

post_author_enable: true
post_date_enable: true
post_category_enable: true
## Post copyright
post_copyright_enable: true

post_copyright_author_enable: true
post_copyright_permalink_enable: true
post_copyright_license_enable: true
post_copyright_license_text: Copyright (c) 2019 <a href="http://creativecommons.org/licenses/by-nc/4.0/">CC-BY-NC-4.0</a> LICENSE
post_copyright_slogan_enable: true
post_copyright_slogan_text: Do you believe in <strong>DESTINY</strong>?
## toc
post_toc_enable: true

# Page
page_title_enable: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: MMMM D, YYYY
time_format: H:mm:ss

# stylesheets loaded in the <head>
stylesheets:
  - /css/style.css

# scripts loaded in the end of the body
scripts:
  - /js/script.js
  - /js/tocbot.min.js
    # tscanlin/tocbot: Build a table of contents from headings in an HTML document.
    # https://github.com/tscanlin/tocbot


# plugin functions
## Mathjax: Math Formula Support
## https://www.mathjax.org
mathjax:
  enable: true
  import: demand # global or demand
  ## global: all pages will load mathjax,this will degrade performance and some grammers may be parsed wrong.
  ## demand: Recommend option,if your post need fomula, you can declare 'mathjax: true' in Front-matter
